insert into tournaments (tournament_id, tournament_name, date, location) values (122, 'Virtual mobile initiative', '2019-04-29', 'Balading');
insert into tournaments (tournament_id, tournament_name, date, location) values (123, 'Organized reciprocal structure', '2019-05-14', 'Chapayeve');
insert into tournaments (tournament_id, tournament_name, date, location) values (124, 'Function-based next generation website', '2019-03-29', 'Nyamanari');
insert into tournaments (tournament_id, tournament_name, date, location) values (125, 'Multi-tiered next generation budgetary management', '2019-05-27', 'Yixi');
insert into tournaments (tournament_id, tournament_name, date, location) values (126, 'Focused content-based internet solution', '2019-03-18', 'Salzburg');
insert into tournaments (tournament_id, tournament_name, date, location) values (127, 'Optional explicit complexity', '2019-04-08', 'La Huerta');
insert into tournaments (tournament_id, tournament_name, date, location) values (128, 'Public-key even-keeled hardware', '2019-07-13', 'Minneapolis');
insert into tournaments (tournament_id, tournament_name, date, location) values (129, 'Sharable bi-directional budgetary management', '2019-03-14', 'Sens');
insert into tournaments (tournament_id, tournament_name, date, location) values (130, 'Ergonomic global capability', '2019-08-31', 'Néa Éfesos');
insert into tournaments (tournament_id, tournament_name, date, location) values (131, 'Optional radical firmware', '2019-12-22', 'Kurkino');
insert into tournaments (tournament_id, tournament_name, date, location) values (132, 'Devolved analyzing instruction set', '2019-01-19', 'Joaquín V. González');
insert into tournaments (tournament_id, tournament_name, date, location) values (133, 'Multi-channelled directional matrix', '2019-01-31', 'Września');
insert into tournaments (tournament_id, tournament_name, date, location) values (134, 'Decentralized systemic toolset', '2019-09-14', 'Sundsvall');
insert into tournaments (tournament_id, tournament_name, date, location) values (135, 'Upgradable grid-enabled circuit', '2019-03-20', 'Dongping');
insert into tournaments (tournament_id, tournament_name, date, location) values (136, 'Re-contextualized directional utilisation', '2019-05-14', 'Las Palmas');
insert into tournaments (tournament_id, tournament_name, date, location) values (137, 'Compatible explicit paradigm', '2019-08-19', 'Mulan');
insert into tournaments (tournament_id, tournament_name, date, location) values (138, 'Enterprise-wide client-server workforce', '2019-11-15', 'Pirapo');
insert into tournaments (tournament_id, tournament_name, date, location) values (139, 'Networked radical neural-net', '2019-12-19', 'Ban Houakhoua');
insert into tournaments (tournament_id, tournament_name, date, location) values (140, 'Re-engineered multi-state open architecture', '2019-08-15', 'Bode Sadu');
insert into tournaments (tournament_id, tournament_name, date, location) values (141, 'Inverse neutral contingency', '2019-04-10', 'Kabulusan');
insert into tournaments (tournament_id, tournament_name, date, location) values (142, 'Distributed high-level solution', '2019-03-10', 'Anfusi');
insert into tournaments (tournament_id, tournament_name, date, location) values (143, 'Enterprise-wide non-volatile portal', '2019-04-08', 'Skoura');
insert into tournaments (tournament_id, tournament_name, date, location) values (144, 'Right-sized 24/7 projection', '2019-10-25', 'Odawara');
insert into tournaments (tournament_id, tournament_name, date, location) values (145, 'Synchronised context-sensitive utilisation', '2019-07-30', 'Jianggu');
insert into tournaments (tournament_id, tournament_name, date, location) values (146, 'Programmable zero administration application', '2019-08-07', 'Krasnaya Gorka');
insert into tournaments (tournament_id, tournament_name, date, location) values (147, 'Innovative fault-tolerant focus group', '2019-08-26', 'Buda-Kashalyova');
insert into tournaments (tournament_id, tournament_name, date, location) values (148, 'Customer-focused dedicated budgetary management', '2019-09-26', 'Thị Trấn Yên Phú');
insert into tournaments (tournament_id, tournament_name, date, location) values (149, 'Universal bottom-line matrix', '2019-09-24', 'Stockholm');
insert into tournaments (tournament_id, tournament_name, date, location) values (150, 'Synchronised grid-enabled throughput', '2019-03-09', 'Hamonggolele');
insert into tournaments (tournament_id, tournament_name, date, location) values (151, 'Face to face non-volatile application', '2019-05-10', 'Huanchaco');
insert into tournaments (tournament_id, tournament_name, date, location) values (152, 'Self-enabling composite knowledge base', '2019-04-06', 'Henglian');
insert into tournaments (tournament_id, tournament_name, date, location) values (153, 'User-friendly logistical knowledge user', '2019-01-16', 'Imeni Tsyurupy');
insert into tournaments (tournament_id, tournament_name, date, location) values (154, 'Robust 3rd generation initiative', '2019-08-20', 'Sanjiao');
insert into tournaments (tournament_id, tournament_name, date, location) values (155, 'Focused system-worthy neural-net', '2019-05-19', 'Hefu');
insert into tournaments (tournament_id, tournament_name, date, location) values (156, 'Reverse-engineered tangible initiative', '2019-01-30', 'Goseong');
insert into tournaments (tournament_id, tournament_name, date, location) values (157, 'Stand-alone high-level productivity', '2019-03-17', 'Ndendé');
insert into tournaments (tournament_id, tournament_name, date, location) values (158, 'Adaptive attitude-oriented product', '2019-11-15', 'Cola');
insert into tournaments (tournament_id, tournament_name, date, location) values (159, 'Object-based encompassing matrix', '2019-05-24', 'Anáfi');
insert into tournaments (tournament_id, tournament_name, date, location) values (160, 'Open-source tertiary workforce', '2019-01-05', 'Lihu');
insert into tournaments (tournament_id, tournament_name, date, location) values (161, 'Automated grid-enabled infrastructure', '2019-08-19', 'Dasha');
insert into tournaments (tournament_id, tournament_name, date, location) values (162, 'Team-oriented zero tolerance website', '2019-10-30', 'Sandakan');
insert into tournaments (tournament_id, tournament_name, date, location) values (163, 'Phased web-enabled forecast', '2019-01-09', 'Žirovnica');
insert into tournaments (tournament_id, tournament_name, date, location) values (164, 'Assimilated 6th generation encoding', '2019-02-13', 'Caparrapí');
insert into tournaments (tournament_id, tournament_name, date, location) values (165, 'Diverse zero defect orchestration', '2019-03-05', 'Yefremov');
insert into tournaments (tournament_id, tournament_name, date, location) values (166, 'Quality-focused executive knowledge base', '2019-01-25', 'Bolilao');
insert into tournaments (tournament_id, tournament_name, date, location) values (167, 'Ergonomic scalable task-force', '2019-03-22', 'Shilovo');
insert into tournaments (tournament_id, tournament_name, date, location) values (168, 'Diverse mission-critical hierarchy', '2019-08-31', 'Thị Trấn Yên Phú');
insert into tournaments (tournament_id, tournament_name, date, location) values (169, 'Managed dynamic matrix', '2019-01-15', 'Novokuz’minki');
insert into tournaments (tournament_id, tournament_name, date, location) values (170, 'Expanded context-sensitive matrix', '2019-11-16', 'Quận Mười');
insert into tournaments (tournament_id, tournament_name, date, location) values (171, 'Secured object-oriented core', '2019-10-14', 'La Concepcion');
insert into tournaments (tournament_id, tournament_name, date, location) values (172, 'Cloned grid-enabled matrices', '2019-12-29', 'Himeville');
insert into tournaments (tournament_id, tournament_name, date, location) values (173, 'User-centric tertiary product', '2019-11-20', 'Nagbacalan');
insert into tournaments (tournament_id, tournament_name, date, location) values (174, 'Stand-alone bifurcated open system', '2019-07-25', 'Ciawitali');
insert into tournaments (tournament_id, tournament_name, date, location) values (175, 'Intuitive systematic info-mediaries', '2019-03-28', 'Novozavedennoye');
insert into tournaments (tournament_id, tournament_name, date, location) values (176, 'Expanded fault-tolerant internet solution', '2019-10-25', 'Aktogay');
insert into tournaments (tournament_id, tournament_name, date, location) values (177, 'Proactive exuding ability', '2019-05-23', 'Songshan');
insert into tournaments (tournament_id, tournament_name, date, location) values (178, 'Realigned stable architecture', '2019-05-15', 'Monrovia');
insert into tournaments (tournament_id, tournament_name, date, location) values (179, 'Seamless neutral local area network', '2019-09-10', 'Kawayan');
insert into tournaments (tournament_id, tournament_name, date, location) values (180, 'Switchable directional hierarchy', '2019-10-14', 'Moutnice');
insert into tournaments (tournament_id, tournament_name, date, location) values (181, 'De-engineered radical protocol', '2019-04-20', 'Jarry');
insert into tournaments (tournament_id, tournament_name, date, location) values (182, 'Optimized eco-centric complexity', '2019-08-10', 'Kanekomachi');
insert into tournaments (tournament_id, tournament_name, date, location) values (183, 'Focused fault-tolerant strategy', '2019-11-19', 'Lesnoy');
insert into tournaments (tournament_id, tournament_name, date, location) values (184, 'Assimilated systematic secured line', '2019-11-03', 'Lewotukan');
insert into tournaments (tournament_id, tournament_name, date, location) values (185, 'Front-line responsive neural-net', '2019-08-28', 'Kissimmee');
insert into tournaments (tournament_id, tournament_name, date, location) values (186, 'Switchable motivating projection', '2019-02-21', 'Chaeryŏng-ŭp');
insert into tournaments (tournament_id, tournament_name, date, location) values (187, 'Organic impactful contingency', '2019-01-10', 'Tvarožná');
insert into tournaments (tournament_id, tournament_name, date, location) values (188, 'Horizontal responsive local area network', '2019-12-19', 'Esfarāyen');
insert into tournaments (tournament_id, tournament_name, date, location) values (189, 'Team-oriented systemic budgetary management', '2019-03-30', 'Balauring');
insert into tournaments (tournament_id, tournament_name, date, location) values (190, 'Monitored leading edge matrix', '2019-01-11', 'Piuí');
insert into tournaments (tournament_id, tournament_name, date, location) values (191, 'Compatible analyzing installation', '2019-08-12', 'Paraíso das Águas');
insert into tournaments (tournament_id, tournament_name, date, location) values (192, 'Distributed 24/7 instruction set', '2019-04-09', 'Aknīste');
insert into tournaments (tournament_id, tournament_name, date, location) values (193, 'Operative client-driven open architecture', '2019-07-12', 'Senneterre');
insert into tournaments (tournament_id, tournament_name, date, location) values (194, 'Streamlined uniform local area network', '2019-09-26', 'Gambalidio');
insert into tournaments (tournament_id, tournament_name, date, location) values (195, 'Profound grid-enabled initiative', '2019-03-22', 'Bålsta');
insert into tournaments (tournament_id, tournament_name, date, location) values (196, 'Open-architected maximized circuit', '2019-09-07', 'Hepo');
insert into tournaments (tournament_id, tournament_name, date, location) values (197, 'Multi-lateral background challenge', '2019-01-22', 'Bangassou');
insert into tournaments (tournament_id, tournament_name, date, location) values (198, 'Multi-channelled real-time success', '2019-11-19', 'Ciampea');
insert into tournaments (tournament_id, tournament_name, date, location) values (199, 'Upgradable directional function', '2019-05-28', 'Payaman');
insert into tournaments (tournament_id, tournament_name, date, location) values (200, 'Programmable web-enabled neural-net', '2019-12-23', 'Di Linh');
insert into tournaments (tournament_id, tournament_name, date, location) values (201, 'Extended solution-oriented adapter', '2019-05-03', 'Lappajärvi');
insert into tournaments (tournament_id, tournament_name, date, location) values (202, 'Business-focused cohesive capacity', '2019-01-04', 'Xiongzhou');
insert into tournaments (tournament_id, tournament_name, date, location) values (203, 'Profound zero administration implementation', '2019-12-18', 'Stebnyk');
insert into tournaments (tournament_id, tournament_name, date, location) values (204, 'Centralized 5th generation support', '2019-12-18', 'Cabanas');
insert into tournaments (tournament_id, tournament_name, date, location) values (205, 'Implemented exuding application', '2019-05-01', 'Frederiksberg');
insert into tournaments (tournament_id, tournament_name, date, location) values (206, 'Open-architected scalable policy', '2019-04-30', 'Sankanan');
insert into tournaments (tournament_id, tournament_name, date, location) values (207, 'Multi-lateral upward-trending paradigm', '2019-09-03', 'Tyshkivka');
insert into tournaments (tournament_id, tournament_name, date, location) values (208, 'Innovative optimizing interface', '2019-04-06', 'Anse Boileau');
insert into tournaments (tournament_id, tournament_name, date, location) values (209, 'Universal background methodology', '2019-07-26', 'Tajike’abati');
insert into tournaments (tournament_id, tournament_name, date, location) values (210, 'Networked maximized adapter', '2019-03-06', 'Novoanninskiy');
insert into tournaments (tournament_id, tournament_name, date, location) values (211, 'Managed neutral access', '2019-02-24', 'La Falda');
insert into tournaments (tournament_id, tournament_name, date, location) values (212, 'Inverse full-range installation', '2019-11-13', 'Boncis');
insert into tournaments (tournament_id, tournament_name, date, location) values (213, 'Distributed even-keeled knowledge user', '2019-07-06', 'Mingyu');
insert into tournaments (tournament_id, tournament_name, date, location) values (214, 'Customizable non-volatile leverage', '2019-08-08', 'Mtimbira');
insert into tournaments (tournament_id, tournament_name, date, location) values (215, 'Organic user-facing challenge', '2019-07-01', 'Kuching');
insert into tournaments (tournament_id, tournament_name, date, location) values (216, 'Versatile leading edge product', '2019-05-22', 'Järfälla');
insert into tournaments (tournament_id, tournament_name, date, location) values (217, 'Programmable fresh-thinking emulation', '2019-12-10', 'U Minh');
insert into tournaments (tournament_id, tournament_name, date, location) values (218, 'Vision-oriented content-based workforce', '2019-11-22', 'Chak Two Hundred Forty-Nine TDA');
insert into tournaments (tournament_id, tournament_name, date, location) values (219, 'Synergistic modular architecture', '2019-05-25', 'Salcedo');
insert into tournaments (tournament_id, tournament_name, date, location) values (220, 'Enterprise-wide secondary intranet', '2019-06-17', 'Guadalupe');
insert into tournaments (tournament_id, tournament_name, date, location) values (221, 'Sharable contextually-based installation', '2019-02-18', 'Karangharjo');
insert into tournaments (tournament_id, tournament_name, date, location) values (222, 'Reverse-engineered logistical secured line', '2019-10-03', 'Westport');
insert into tournaments (tournament_id, tournament_name, date, location) values (223, 'Grass-roots maximized local area network', '2019-03-26', 'Mengyin');
insert into tournaments (tournament_id, tournament_name, date, location) values (224, 'Synergized static emulation', '2019-05-18', 'Liaoyang');
insert into tournaments (tournament_id, tournament_name, date, location) values (225, 'Horizontal systematic middleware', '2019-10-13', 'Burgersdorp');
insert into tournaments (tournament_id, tournament_name, date, location) values (226, 'Exclusive grid-enabled framework', '2019-08-25', 'Ollachea');
insert into tournaments (tournament_id, tournament_name, date, location) values (227, 'Managed discrete installation', '2019-10-13', 'Tahilt');
insert into tournaments (tournament_id, tournament_name, date, location) values (228, 'Future-proofed next generation Graphic Interface', '2019-10-28', 'Ueda');
insert into tournaments (tournament_id, tournament_name, date, location) values (229, 'Exclusive non-volatile knowledge user', '2019-06-20', 'Tongqing');
insert into tournaments (tournament_id, tournament_name, date, location) values (230, 'Integrated client-server model', '2019-10-02', 'Aseri');
insert into tournaments (tournament_id, tournament_name, date, location) values (231, 'Synchronised even-keeled collaboration', '2019-10-29', 'Jambu');
insert into tournaments (tournament_id, tournament_name, date, location) values (232, 'Stand-alone scalable initiative', '2019-09-01', 'Chengguan');
insert into tournaments (tournament_id, tournament_name, date, location) values (233, 'Multi-tiered leading edge standardization', '2019-07-02', 'Bontoc');
insert into tournaments (tournament_id, tournament_name, date, location) values (234, 'Innovative high-level instruction set', '2019-07-31', 'São Lourenço');
insert into tournaments (tournament_id, tournament_name, date, location) values (235, 'De-engineered mission-critical matrix', '2019-06-06', 'Kobrinskoye');
insert into tournaments (tournament_id, tournament_name, date, location) values (236, 'Phased regional productivity', '2019-03-26', 'Saeul');
insert into tournaments (tournament_id, tournament_name, date, location) values (237, 'Monitored asymmetric utilisation', '2019-09-29', 'Tsagaan-Owoo');
insert into tournaments (tournament_id, tournament_name, date, location) values (238, 'Managed scalable conglomeration', '2019-12-20', 'Kōnosu');
insert into tournaments (tournament_id, tournament_name, date, location) values (239, 'Assimilated multi-state synergy', '2019-02-21', 'Oshnavīyeh');
insert into tournaments (tournament_id, tournament_name, date, location) values (240, 'Mandatory real-time open system', '2019-12-27', 'Vrbno pod Pradědem');
insert into tournaments (tournament_id, tournament_name, date, location) values (241, 'Fundamental optimizing forecast', '2019-06-04', 'Kaminoyama');
insert into tournaments (tournament_id, tournament_name, date, location) values (242, 'Customer-focused even-keeled firmware', '2019-01-10', 'Andong');
insert into tournaments (tournament_id, tournament_name, date, location) values (243, 'Horizontal human-resource attitude', '2019-06-08', 'Greeley');
insert into tournaments (tournament_id, tournament_name, date, location) values (244, 'Stand-alone mission-critical application', '2019-07-06', 'Buenos Aires');
insert into tournaments (tournament_id, tournament_name, date, location) values (245, 'Managed real-time time-frame', '2019-12-26', 'Kharagauli');
insert into tournaments (tournament_id, tournament_name, date, location) values (246, 'Phased user-facing database', '2019-11-10', 'Bua Yai');
insert into tournaments (tournament_id, tournament_name, date, location) values (247, 'Future-proofed local access', '2019-08-26', 'Tuchów');
insert into tournaments (tournament_id, tournament_name, date, location) values (248, 'Down-sized demand-driven throughput', '2019-01-19', 'Los Angeles');
insert into tournaments (tournament_id, tournament_name, date, location) values (249, 'Multi-layered zero administration migration', '2019-05-05', 'Duncans');
insert into tournaments (tournament_id, tournament_name, date, location) values (250, 'Reactive stable toolset', '2019-07-09', 'Pont-Audemer');
insert into tournaments (tournament_id, tournament_name, date, location) values (251, 'Profound uniform knowledge user', '2019-06-28', 'Banaybanay');
insert into tournaments (tournament_id, tournament_name, date, location) values (252, 'Balanced demand-driven leverage', '2019-05-13', 'Semënovskoye');
insert into tournaments (tournament_id, tournament_name, date, location) values (253, 'Re-engineered reciprocal adapter', '2019-09-03', 'Ylämaa');
insert into tournaments (tournament_id, tournament_name, date, location) values (254, 'Phased impactful algorithm', '2019-09-24', 'Saint-Laurent-du-Var');
insert into tournaments (tournament_id, tournament_name, date, location) values (255, 'Stand-alone interactive moratorium', '2019-10-15', 'Proletar');
insert into tournaments (tournament_id, tournament_name, date, location) values (256, 'Versatile hybrid workforce', '2019-03-12', 'Katoúna');
insert into tournaments (tournament_id, tournament_name, date, location) values (257, 'Open-architected multi-tasking intranet', '2019-11-11', 'Foz Giraldo');
insert into tournaments (tournament_id, tournament_name, date, location) values (258, 'Expanded foreground knowledge base', '2019-04-18', 'La Peña');
insert into tournaments (tournament_id, tournament_name, date, location) values (259, 'Reactive heuristic success', '2019-03-31', 'Qila Abdullāh');
insert into tournaments (tournament_id, tournament_name, date, location) values (260, 'Persistent directional model', '2019-06-22', 'Puamata');
insert into tournaments (tournament_id, tournament_name, date, location) values (261, 'Programmable bandwidth-monitored capability', '2019-07-30', 'Huangma');
insert into tournaments (tournament_id, tournament_name, date, location) values (262, 'Devolved methodical migration', '2019-12-27', 'Matanzas');
insert into tournaments (tournament_id, tournament_name, date, location) values (263, 'Team-oriented holistic groupware', '2019-07-23', 'Angasmarca');
insert into tournaments (tournament_id, tournament_name, date, location) values (264, 'Integrated tertiary Graphic Interface', '2019-05-29', 'Bintawan');
insert into tournaments (tournament_id, tournament_name, date, location) values (265, 'Total multimedia open system', '2019-01-04', 'Harrismith');
insert into tournaments (tournament_id, tournament_name, date, location) values (266, 'Multi-layered uniform portal', '2019-10-01', 'Hongqi');
insert into tournaments (tournament_id, tournament_name, date, location) values (267, 'Cross-group solution-oriented time-frame', '2019-01-16', 'Orivesi');
insert into tournaments (tournament_id, tournament_name, date, location) values (268, 'Stand-alone multimedia middleware', '2019-11-16', 'Padang');
insert into tournaments (tournament_id, tournament_name, date, location) values (269, 'User-centric exuding open system', '2019-08-19', 'Haicheng');
insert into tournaments (tournament_id, tournament_name, date, location) values (270, 'Customer-focused interactive benchmark', '2019-01-01', 'Al ‘Āliyah');
insert into tournaments (tournament_id, tournament_name, date, location) values (271, 'Object-based optimizing access', '2019-05-31', 'Hà Đông');
insert into tournaments (tournament_id, tournament_name, date, location) values (272, 'Re-contextualized bi-directional Graphic Interface', '2019-10-16', 'Qufu');
insert into tournaments (tournament_id, tournament_name, date, location) values (273, 'Devolved asynchronous middleware', '2019-06-20', 'Chifeng');
insert into tournaments (tournament_id, tournament_name, date, location) values (274, 'Optimized full-range utilisation', '2019-11-09', 'Rakszawa');
insert into tournaments (tournament_id, tournament_name, date, location) values (275, 'Profit-focused context-sensitive service-desk', '2019-08-30', 'Ínfias');
insert into tournaments (tournament_id, tournament_name, date, location) values (276, 'Streamlined foreground system engine', '2019-01-12', 'Chambéry');
insert into tournaments (tournament_id, tournament_name, date, location) values (277, 'Enhanced explicit moratorium', '2019-09-29', 'Shangmofang');
insert into tournaments (tournament_id, tournament_name, date, location) values (278, 'Horizontal 24/7 project', '2019-09-24', 'Wasquehal');
insert into tournaments (tournament_id, tournament_name, date, location) values (279, 'Persevering optimizing solution', '2019-08-30', 'Cocachacra');
insert into tournaments (tournament_id, tournament_name, date, location) values (280, 'Multi-layered fresh-thinking parallelism', '2019-07-16', 'Aguadas');
insert into tournaments (tournament_id, tournament_name, date, location) values (281, 'Compatible directional encoding', '2019-09-28', 'Sobral');
insert into tournaments (tournament_id, tournament_name, date, location) values (282, 'Profit-focused attitude-oriented focus group', '2019-07-07', 'Ngunguru');
insert into tournaments (tournament_id, tournament_name, date, location) values (283, 'Horizontal bifurcated website', '2019-08-14', 'Seremban');
insert into tournaments (tournament_id, tournament_name, date, location) values (284, 'Automated web-enabled task-force', '2019-09-06', 'Nice');
insert into tournaments (tournament_id, tournament_name, date, location) values (285, 'Digitized dedicated intranet', '2019-02-10', 'Əhmədbəyli');
insert into tournaments (tournament_id, tournament_name, date, location) values (286, 'Team-oriented actuating concept', '2019-05-26', 'La Rochelle');
insert into tournaments (tournament_id, tournament_name, date, location) values (287, 'Robust homogeneous productivity', '2019-06-20', 'Gambut');
insert into tournaments (tournament_id, tournament_name, date, location) values (288, 'Extended 4th generation core', '2019-10-01', 'Calibishie');
insert into tournaments (tournament_id, tournament_name, date, location) values (289, 'Seamless client-driven adapter', '2019-06-22', 'Dobrá');
insert into tournaments (tournament_id, tournament_name, date, location) values (290, 'Synergistic upward-trending array', '2019-10-19', 'Talaibon');
insert into tournaments (tournament_id, tournament_name, date, location) values (291, 'Business-focused fault-tolerant system engine', '2019-10-01', 'Tinumpuk');
insert into tournaments (tournament_id, tournament_name, date, location) values (292, 'Reactive empowering encoding', '2019-03-03', 'Talghar');
insert into tournaments (tournament_id, tournament_name, date, location) values (293, 'Robust reciprocal leverage', '2019-08-20', 'Songnim');
insert into tournaments (tournament_id, tournament_name, date, location) values (294, 'Organic 6th generation budgetary management', '2019-03-04', 'Tetovo');
insert into tournaments (tournament_id, tournament_name, date, location) values (295, 'Triple-buffered holistic core', '2019-07-20', 'Bajiao');
insert into tournaments (tournament_id, tournament_name, date, location) values (296, 'Focused high-level portal', '2019-11-20', 'Belalcazar');
insert into tournaments (tournament_id, tournament_name, date, location) values (297, 'Polarised contextually-based focus group', '2019-08-03', 'Belung Satu');
insert into tournaments (tournament_id, tournament_name, date, location) values (298, 'Pre-emptive fault-tolerant array', '2019-11-29', 'Quinta do Sobrado');
insert into tournaments (tournament_id, tournament_name, date, location) values (299, 'Up-sized zero defect database', '2019-07-17', 'Akebielidou');
insert into tournaments (tournament_id, tournament_name, date, location) values (300, 'Operative radical intranet', '2019-09-17', 'Colorado');
insert into tournaments (tournament_id, tournament_name, date, location) values (301, 'Fundamental demand-driven software', '2019-05-17', 'Caomiao');
insert into tournaments (tournament_id, tournament_name, date, location) values (302, 'Operative zero tolerance instruction set', '2019-08-22', 'Néa Palátia');
insert into tournaments (tournament_id, tournament_name, date, location) values (303, 'Balanced static architecture', '2019-11-02', 'Wangtai');
insert into tournaments (tournament_id, tournament_name, date, location) values (304, 'Right-sized eco-centric monitoring', '2019-10-07', 'Raemude');
insert into tournaments (tournament_id, tournament_name, date, location) values (305, 'Re-engineered motivating help-desk', '2019-11-04', 'Tsimasham');
insert into tournaments (tournament_id, tournament_name, date, location) values (306, 'Re-contextualized content-based middleware', '2019-10-28', 'Sagana');
insert into tournaments (tournament_id, tournament_name, date, location) values (307, 'Grass-roots contextually-based installation', '2019-10-29', 'Youhao');
insert into tournaments (tournament_id, tournament_name, date, location) values (308, 'Implemented radical function', '2019-09-06', 'Ābyek');
insert into tournaments (tournament_id, tournament_name, date, location) values (309, 'Streamlined asynchronous monitoring', '2019-11-05', 'Daultāla');
insert into tournaments (tournament_id, tournament_name, date, location) values (310, 'Multi-tiered discrete artificial intelligence', '2019-07-30', 'Lendangara Satu');
insert into tournaments (tournament_id, tournament_name, date, location) values (311, 'Assimilated eco-centric synergy', '2019-10-10', 'Belén');
insert into tournaments (tournament_id, tournament_name, date, location) values (312, 'Realigned user-facing database', '2019-09-05', 'Ma‘lūlā');
insert into tournaments (tournament_id, tournament_name, date, location) values (313, 'Enterprise-wide interactive collaboration', '2019-09-05', 'Sobral');
insert into tournaments (tournament_id, tournament_name, date, location) values (314, 'Managed stable project', '2019-06-05', 'Manolás');
insert into tournaments (tournament_id, tournament_name, date, location) values (315, 'Stand-alone interactive local area network', '2019-10-03', 'Saint Louis');
insert into tournaments (tournament_id, tournament_name, date, location) values (316, 'Universal 24 hour model', '2019-09-24', 'Hong Kong');
insert into tournaments (tournament_id, tournament_name, date, location) values (317, 'De-engineered systematic emulation', '2019-07-26', 'Roche Terre');
insert into tournaments (tournament_id, tournament_name, date, location) values (318, 'Ergonomic 4th generation artificial intelligence', '2019-02-13', 'Baitouli');
insert into tournaments (tournament_id, tournament_name, date, location) values (319, 'Pre-emptive empowering help-desk', '2019-12-03', 'Saguday');
insert into tournaments (tournament_id, tournament_name, date, location) values (320, 'Distributed bifurcated support', '2019-09-30', 'Qinghe');
insert into tournaments (tournament_id, tournament_name, date, location) values (321, 'Business-focused transitional middleware', '2019-04-21', 'Tabon');
