insert into tournaments (tournament_id, tournament_name, date, location) values (322, 'Mandatory dedicated ability', '2016-04-11', 'Thị Trấn Quảng Uyên');
insert into tournaments (tournament_id, tournament_name, date, location) values (323, 'Adaptive systemic encryption', '2016-02-03', 'Antsirabe');
insert into tournaments (tournament_id, tournament_name, date, location) values (324, 'Compatible human-resource knowledge user', '2016-04-26', 'Obninsk');
insert into tournaments (tournament_id, tournament_name, date, location) values (325, 'Team-oriented stable architecture', '2017-04-16', 'Issoire');
insert into tournaments (tournament_id, tournament_name, date, location) values (326, 'Visionary solution-oriented benchmark', '2016-01-02', 'Langtad');
insert into tournaments (tournament_id, tournament_name, date, location) values (327, 'Business-focused motivating model', '2017-03-06', 'Sandy Bay');
insert into tournaments (tournament_id, tournament_name, date, location) values (328, 'Triple-buffered regional focus group', '2016-11-08', 'Swindon');
insert into tournaments (tournament_id, tournament_name, date, location) values (329, 'Open-source incremental solution', '2016-04-05', 'Abeokuta');
insert into tournaments (tournament_id, tournament_name, date, location) values (330, 'Operative optimizing software', '2016-01-13', 'Badovinci');
insert into tournaments (tournament_id, tournament_name, date, location) values (331, 'Adaptive mobile success', '2017-03-17', 'Ala');
insert into tournaments (tournament_id, tournament_name, date, location) values (332, 'Re-contextualized homogeneous function', '2017-10-12', 'Zarszyn');
insert into tournaments (tournament_id, tournament_name, date, location) values (333, 'Pre-emptive user-facing methodology', '2017-05-04', 'Al Bawīţī');
insert into tournaments (tournament_id, tournament_name, date, location) values (334, 'Focused object-oriented product', '2017-08-19', 'Broniszewice');
insert into tournaments (tournament_id, tournament_name, date, location) values (335, 'Cross-group scalable process improvement', '2016-07-30', 'Pulosari');
insert into tournaments (tournament_id, tournament_name, date, location) values (336, 'User-friendly leading edge hierarchy', '2016-05-31', 'Michałowo');
insert into tournaments (tournament_id, tournament_name, date, location) values (337, 'Triple-buffered non-volatile throughput', '2017-03-07', 'Kumla');
insert into tournaments (tournament_id, tournament_name, date, location) values (338, 'Front-line background framework', '2016-06-17', 'Canauay');
insert into tournaments (tournament_id, tournament_name, date, location) values (339, 'Progressive responsive hardware', '2017-05-26', 'Chiscas');
insert into tournaments (tournament_id, tournament_name, date, location) values (340, 'Streamlined background forecast', '2017-03-06', 'Okaya');
insert into tournaments (tournament_id, tournament_name, date, location) values (341, 'Profit-focused regional utilisation', '2017-08-25', 'New Sibonga');
insert into tournaments (tournament_id, tournament_name, date, location) values (342, 'Configurable bottom-line utilisation', '2016-01-06', 'Kotaagung');
insert into tournaments (tournament_id, tournament_name, date, location) values (343, 'Up-sized multi-tasking functionalities', '2016-04-24', 'Thành Phố Thái Bình');
insert into tournaments (tournament_id, tournament_name, date, location) values (344, 'Public-key upward-trending groupware', '2017-05-23', 'Ruma');
insert into tournaments (tournament_id, tournament_name, date, location) values (345, 'Expanded heuristic frame', '2016-09-19', 'Citarik');
insert into tournaments (tournament_id, tournament_name, date, location) values (346, 'Seamless needs-based leverage', '2016-12-05', 'Nongoma');
insert into tournaments (tournament_id, tournament_name, date, location) values (347, 'Intuitive multi-state concept', '2017-06-07', 'Irupi');
insert into tournaments (tournament_id, tournament_name, date, location) values (348, 'Programmable value-added website', '2016-03-26', 'Ciudad Bolivia');
insert into tournaments (tournament_id, tournament_name, date, location) values (349, 'Organic impactful extranet', '2016-10-05', 'Alexandria');
insert into tournaments (tournament_id, tournament_name, date, location) values (350, 'User-friendly contextually-based implementation', '2016-07-16', 'João Monlevade');
insert into tournaments (tournament_id, tournament_name, date, location) values (351, 'Centralized intangible installation', '2016-09-28', 'Coronel Fabriciano');
insert into tournaments (tournament_id, tournament_name, date, location) values (352, 'Down-sized mission-critical workforce', '2016-01-22', 'Butigui');
insert into tournaments (tournament_id, tournament_name, date, location) values (353, 'Multi-layered impactful software', '2017-06-09', 'Quintã');
insert into tournaments (tournament_id, tournament_name, date, location) values (354, 'Extended bi-directional monitoring', '2016-11-08', 'Bilajari');
insert into tournaments (tournament_id, tournament_name, date, location) values (355, 'Stand-alone needs-based functionalities', '2017-08-13', 'Vigan');
insert into tournaments (tournament_id, tournament_name, date, location) values (356, 'Mandatory responsive challenge', '2016-09-12', 'Yangdang');
insert into tournaments (tournament_id, tournament_name, date, location) values (357, 'Configurable mobile service-desk', '2016-03-04', 'Ebak');
insert into tournaments (tournament_id, tournament_name, date, location) values (358, 'Reverse-engineered homogeneous complexity', '2017-07-22', 'Itbayat');
insert into tournaments (tournament_id, tournament_name, date, location) values (359, 'Persevering executive benchmark', '2016-07-19', 'Banfora');
insert into tournaments (tournament_id, tournament_name, date, location) values (360, 'Configurable non-volatile product', '2016-11-04', 'Bilajari');
insert into tournaments (tournament_id, tournament_name, date, location) values (361, 'Multi-lateral client-server approach', '2017-10-24', 'Kohila');
insert into tournaments (tournament_id, tournament_name, date, location) values (362, 'Diverse grid-enabled superstructure', '2017-03-13', 'Huayacundo Arma');
insert into tournaments (tournament_id, tournament_name, date, location) values (363, 'Vision-oriented 24 hour ability', '2016-10-10', 'Šmartno pri Litiji');
insert into tournaments (tournament_id, tournament_name, date, location) values (364, 'Secured didactic productivity', '2016-05-10', 'Qikeshu');
insert into tournaments (tournament_id, tournament_name, date, location) values (365, 'Distributed background pricing structure', '2016-08-31', 'Karamat');
insert into tournaments (tournament_id, tournament_name, date, location) values (366, 'Reduced modular leverage', '2016-03-23', 'Bobigny');
insert into tournaments (tournament_id, tournament_name, date, location) values (367, 'Persevering optimizing initiative', '2016-03-16', 'Xingang');
insert into tournaments (tournament_id, tournament_name, date, location) values (368, 'Optional intermediate strategy', '2016-12-07', 'Pasirpanjang');
insert into tournaments (tournament_id, tournament_name, date, location) values (369, 'Enterprise-wide zero defect synergy', '2017-12-15', 'Uurainen');
insert into tournaments (tournament_id, tournament_name, date, location) values (370, 'Focused neutral archive', '2017-04-14', 'Springfield');
insert into tournaments (tournament_id, tournament_name, date, location) values (371, 'Synergistic content-based website', '2016-12-24', 'Jiangdong');
insert into tournaments (tournament_id, tournament_name, date, location) values (372, 'Diverse local instruction set', '2016-09-04', 'Mesquite');
insert into tournaments (tournament_id, tournament_name, date, location) values (373, 'Multi-layered neutral utilisation', '2016-08-25', 'Orikum');
insert into tournaments (tournament_id, tournament_name, date, location) values (374, 'Reactive stable benchmark', '2016-11-26', 'Pancas');
insert into tournaments (tournament_id, tournament_name, date, location) values (375, 'Reactive contextually-based model', '2017-12-22', 'Sremska Mitrovica');
insert into tournaments (tournament_id, tournament_name, date, location) values (376, 'Universal fault-tolerant hub', '2016-12-19', 'Yuqian');
insert into tournaments (tournament_id, tournament_name, date, location) values (377, 'Grass-roots encompassing orchestration', '2016-09-19', 'El Obeid');
insert into tournaments (tournament_id, tournament_name, date, location) values (378, 'Open-architected clear-thinking info-mediaries', '2017-09-10', 'Socorro');
insert into tournaments (tournament_id, tournament_name, date, location) values (379, 'Intuitive bifurcated service-desk', '2016-10-09', 'Kumberg');
insert into tournaments (tournament_id, tournament_name, date, location) values (380, 'Proactive full-range projection', '2017-02-21', 'Ngangpo');
insert into tournaments (tournament_id, tournament_name, date, location) values (381, 'User-friendly mission-critical installation', '2016-11-08', 'Banqiaodian');
insert into tournaments (tournament_id, tournament_name, date, location) values (382, 'Networked actuating array', '2017-10-30', 'Lutowiska');
insert into tournaments (tournament_id, tournament_name, date, location) values (383, 'Expanded context-sensitive synergy', '2016-10-17', 'Fort Pierce');
insert into tournaments (tournament_id, tournament_name, date, location) values (384, 'Extended explicit concept', '2017-05-03', 'Panyam');
insert into tournaments (tournament_id, tournament_name, date, location) values (385, 'Versatile non-volatile monitoring', '2016-01-30', 'Thun');
insert into tournaments (tournament_id, tournament_name, date, location) values (386, 'Advanced stable budgetary management', '2016-02-10', 'Hexi');
insert into tournaments (tournament_id, tournament_name, date, location) values (387, 'Robust responsive frame', '2017-05-09', 'Leduc');
insert into tournaments (tournament_id, tournament_name, date, location) values (388, 'Ameliorated mission-critical benchmark', '2016-01-13', 'Bardo');
insert into tournaments (tournament_id, tournament_name, date, location) values (389, 'Profound radical access', '2016-07-27', 'Kruševica');
insert into tournaments (tournament_id, tournament_name, date, location) values (390, 'Open-source 4th generation groupware', '2016-02-13', 'Kamirenjaku');
insert into tournaments (tournament_id, tournament_name, date, location) values (391, 'Diverse zero administration info-mediaries', '2017-10-24', 'Pengbu');
insert into tournaments (tournament_id, tournament_name, date, location) values (392, 'Public-key grid-enabled capacity', '2017-02-01', 'Kinzan');
insert into tournaments (tournament_id, tournament_name, date, location) values (393, 'Front-line uniform focus group', '2016-05-24', 'Jangdam');
insert into tournaments (tournament_id, tournament_name, date, location) values (394, 'Profit-focused background throughput', '2016-05-11', 'Delgermörön');
insert into tournaments (tournament_id, tournament_name, date, location) values (395, 'Cloned neutral projection', '2017-03-11', 'Krasne');
insert into tournaments (tournament_id, tournament_name, date, location) values (396, 'Monitored intangible middleware', '2017-03-12', 'Stamboliyski');
insert into tournaments (tournament_id, tournament_name, date, location) values (397, 'Balanced executive knowledge user', '2017-07-31', 'Tân Sơn');
insert into tournaments (tournament_id, tournament_name, date, location) values (398, 'Synergized bifurcated Graphic Interface', '2017-11-10', 'Lere');
insert into tournaments (tournament_id, tournament_name, date, location) values (399, 'Implemented systemic task-force', '2017-01-08', 'Šipovo');
insert into tournaments (tournament_id, tournament_name, date, location) values (400, 'Profound 24 hour alliance', '2017-01-29', 'Kafr Zaytā');
insert into tournaments (tournament_id, tournament_name, date, location) values (401, 'Public-key next generation local area network', '2017-12-29', 'Ryazan’');
insert into tournaments (tournament_id, tournament_name, date, location) values (402, 'Optional intermediate hub', '2017-11-03', 'Palangan');
insert into tournaments (tournament_id, tournament_name, date, location) values (403, 'Centralized even-keeled application', '2016-08-19', 'Kalyny');
insert into tournaments (tournament_id, tournament_name, date, location) values (404, 'Organized real-time installation', '2017-01-15', 'Neochórion');
insert into tournaments (tournament_id, tournament_name, date, location) values (405, 'Re-engineered user-facing functionalities', '2016-03-02', 'Beigang');
insert into tournaments (tournament_id, tournament_name, date, location) values (406, 'Cloned solution-oriented core', '2017-11-12', 'Capim Grosso');
insert into tournaments (tournament_id, tournament_name, date, location) values (407, 'Front-line next generation intranet', '2017-05-12', 'Si Somdet');
insert into tournaments (tournament_id, tournament_name, date, location) values (408, 'Assimilated hybrid contingency', '2017-08-06', 'Banjar Pangkungkarung Kangin');
insert into tournaments (tournament_id, tournament_name, date, location) values (409, 'Upgradable intangible internet solution', '2017-11-25', 'Góis');
insert into tournaments (tournament_id, tournament_name, date, location) values (410, 'Multi-channelled systemic attitude', '2016-10-17', 'Pamplona/Iruña');
insert into tournaments (tournament_id, tournament_name, date, location) values (411, 'Devolved content-based infrastructure', '2017-10-13', 'Chengdong');
insert into tournaments (tournament_id, tournament_name, date, location) values (412, 'Centralized bifurcated customer loyalty', '2016-08-07', 'Smolensk');
insert into tournaments (tournament_id, tournament_name, date, location) values (413, 'Team-oriented zero administration application', '2017-12-23', 'General Elizardo Aquino');
insert into tournaments (tournament_id, tournament_name, date, location) values (414, 'Vision-oriented upward-trending architecture', '2016-04-15', 'Stare Kurowo');
insert into tournaments (tournament_id, tournament_name, date, location) values (415, 'Re-engineered contextually-based customer loyalty', '2016-05-30', 'Yifaquan');
insert into tournaments (tournament_id, tournament_name, date, location) values (416, 'Enhanced needs-based info-mediaries', '2017-01-26', 'Shiogama');
insert into tournaments (tournament_id, tournament_name, date, location) values (417, 'Cloned secondary adapter', '2017-07-19', 'Bystré');
insert into tournaments (tournament_id, tournament_name, date, location) values (418, 'Proactive web-enabled approach', '2016-05-08', 'Bagumbayan');
insert into tournaments (tournament_id, tournament_name, date, location) values (419, 'Open-source empowering implementation', '2016-10-28', 'Ballinteer');
insert into tournaments (tournament_id, tournament_name, date, location) values (420, 'Monitored explicit superstructure', '2017-07-23', 'Matangpayang');
insert into tournaments (tournament_id, tournament_name, date, location) values (421, 'Innovative radical migration', '2017-06-21', 'Baiguo');
insert into tournaments (tournament_id, tournament_name, date, location) values (422, 'Enterprise-wide global success', '2017-07-12', 'Ciranca');
insert into tournaments (tournament_id, tournament_name, date, location) values (423, 'Fundamental foreground hub', '2016-03-31', 'Austin');
insert into tournaments (tournament_id, tournament_name, date, location) values (424, 'Cross-group user-facing hub', '2017-10-28', 'Zambujeira');
insert into tournaments (tournament_id, tournament_name, date, location) values (425, 'Programmable next generation capacity', '2017-11-27', 'Nanfeng');
insert into tournaments (tournament_id, tournament_name, date, location) values (426, 'Profit-focused secondary support', '2017-06-08', 'Xing’an');
insert into tournaments (tournament_id, tournament_name, date, location) values (427, 'Configurable fault-tolerant complexity', '2017-03-23', 'Ludbreg');
insert into tournaments (tournament_id, tournament_name, date, location) values (428, 'Up-sized uniform open architecture', '2017-08-30', 'Klyuchevskiy');
insert into tournaments (tournament_id, tournament_name, date, location) values (429, 'Devolved maximized benchmark', '2017-01-09', 'Pakis');
insert into tournaments (tournament_id, tournament_name, date, location) values (430, 'Optimized 4th generation ability', '2016-12-19', 'Małkinia Górna');
insert into tournaments (tournament_id, tournament_name, date, location) values (431, 'Multi-channelled non-volatile Graphical User Interface', '2016-09-09', 'Bahía Blanca');
insert into tournaments (tournament_id, tournament_name, date, location) values (432, 'Front-line systemic adapter', '2017-06-25', 'Suleja');
insert into tournaments (tournament_id, tournament_name, date, location) values (433, 'Enhanced motivating hierarchy', '2016-05-22', 'Chilmāri');
insert into tournaments (tournament_id, tournament_name, date, location) values (434, 'Down-sized homogeneous core', '2017-02-11', 'Duotian');
insert into tournaments (tournament_id, tournament_name, date, location) values (435, 'Proactive non-volatile workforce', '2017-03-26', 'La Tuque');
insert into tournaments (tournament_id, tournament_name, date, location) values (436, 'Universal radical artificial intelligence', '2017-05-09', 'Tak Bai');
insert into tournaments (tournament_id, tournament_name, date, location) values (437, 'Expanded zero tolerance capability', '2017-11-10', 'Cambarus');
insert into tournaments (tournament_id, tournament_name, date, location) values (438, 'Profit-focused real-time projection', '2017-06-13', 'Shāhpur Chākar');
insert into tournaments (tournament_id, tournament_name, date, location) values (439, 'Universal bottom-line monitoring', '2017-01-30', 'Florestópolis');
insert into tournaments (tournament_id, tournament_name, date, location) values (440, 'Front-line multi-state data-warehouse', '2017-05-30', 'Lido');
insert into tournaments (tournament_id, tournament_name, date, location) values (441, 'Operative holistic support', '2016-12-05', 'Xinxing');
insert into tournaments (tournament_id, tournament_name, date, location) values (442, 'Business-focused dedicated matrices', '2017-02-17', 'Santos');
insert into tournaments (tournament_id, tournament_name, date, location) values (443, 'Total intangible archive', '2017-04-13', 'Massawa');
insert into tournaments (tournament_id, tournament_name, date, location) values (444, 'De-engineered dedicated challenge', '2016-11-27', 'Rosice');
insert into tournaments (tournament_id, tournament_name, date, location) values (445, 'Visionary bifurcated middleware', '2016-05-23', 'Cork');
insert into tournaments (tournament_id, tournament_name, date, location) values (446, 'Future-proofed asymmetric moratorium', '2017-02-16', 'Pindi Bhattiān');
insert into tournaments (tournament_id, tournament_name, date, location) values (447, 'Enterprise-wide coherent task-force', '2016-06-19', 'Nanyang');
insert into tournaments (tournament_id, tournament_name, date, location) values (448, 'Virtual systematic help-desk', '2016-02-10', 'Matozinhos');
insert into tournaments (tournament_id, tournament_name, date, location) values (449, 'Mandatory heuristic internet solution', '2017-08-27', 'Boudinar');
insert into tournaments (tournament_id, tournament_name, date, location) values (450, 'Exclusive zero tolerance standardization', '2017-09-09', 'Pasian');
insert into tournaments (tournament_id, tournament_name, date, location) values (451, 'Automated full-range archive', '2016-10-07', 'Askim');
insert into tournaments (tournament_id, tournament_name, date, location) values (452, 'Down-sized upward-trending productivity', '2017-02-02', 'Mombetsu');
insert into tournaments (tournament_id, tournament_name, date, location) values (453, 'Horizontal tertiary leverage', '2016-08-24', 'Eiguliai');
insert into tournaments (tournament_id, tournament_name, date, location) values (454, 'Total incremental extranet', '2016-12-07', 'Gesing');
insert into tournaments (tournament_id, tournament_name, date, location) values (455, 'Enterprise-wide executive policy', '2017-03-24', 'Krajan');
insert into tournaments (tournament_id, tournament_name, date, location) values (456, 'Down-sized regional middleware', '2017-12-17', 'Gorobinci');
insert into tournaments (tournament_id, tournament_name, date, location) values (457, 'Open-architected client-driven hub', '2017-04-05', 'Egindiköl');
insert into tournaments (tournament_id, tournament_name, date, location) values (458, 'De-engineered heuristic migration', '2017-08-13', 'West Kelowna');
insert into tournaments (tournament_id, tournament_name, date, location) values (459, 'Quality-focused intermediate success', '2017-02-03', 'Shimo-furano');
insert into tournaments (tournament_id, tournament_name, date, location) values (460, 'Digitized full-range functionalities', '2016-03-21', 'Çobansığnaq');
insert into tournaments (tournament_id, tournament_name, date, location) values (461, 'Networked exuding projection', '2017-01-12', 'Shaoha');
insert into tournaments (tournament_id, tournament_name, date, location) values (462, 'Customizable empowering collaboration', '2017-08-31', 'Gusong');
insert into tournaments (tournament_id, tournament_name, date, location) values (463, 'Synergized systematic time-frame', '2016-01-30', 'Širvintos');
insert into tournaments (tournament_id, tournament_name, date, location) values (464, 'Universal client-server hardware', '2017-04-17', 'Bronnitsy');
insert into tournaments (tournament_id, tournament_name, date, location) values (465, 'Programmable regional installation', '2017-12-11', 'Keli');
insert into tournaments (tournament_id, tournament_name, date, location) values (466, 'Virtual optimizing secured line', '2017-11-09', 'Chengjiao');
insert into tournaments (tournament_id, tournament_name, date, location) values (467, 'Switchable motivating architecture', '2017-05-21', 'Cabiguan');
insert into tournaments (tournament_id, tournament_name, date, location) values (468, 'Stand-alone even-keeled info-mediaries', '2017-04-25', 'Whittlesea');
insert into tournaments (tournament_id, tournament_name, date, location) values (469, 'Robust 6th generation implementation', '2016-01-19', 'Ipoh');
insert into tournaments (tournament_id, tournament_name, date, location) values (470, 'Exclusive methodical local area network', '2016-12-04', 'Yeniköy');
insert into tournaments (tournament_id, tournament_name, date, location) values (471, 'Virtual composite customer loyalty', '2017-07-31', 'Liloan');
insert into tournaments (tournament_id, tournament_name, date, location) values (472, 'Reduced composite conglomeration', '2017-12-21', 'Kuiyong');
insert into tournaments (tournament_id, tournament_name, date, location) values (473, 'Progressive directional neural-net', '2016-04-27', 'Almaznyy');
insert into tournaments (tournament_id, tournament_name, date, location) values (474, 'Exclusive multimedia utilisation', '2017-03-26', 'Laweueng');
insert into tournaments (tournament_id, tournament_name, date, location) values (475, 'Grass-roots background hierarchy', '2017-12-20', 'Dębno');
insert into tournaments (tournament_id, tournament_name, date, location) values (476, 'Self-enabling upward-trending productivity', '2017-05-16', 'Artesianón');
insert into tournaments (tournament_id, tournament_name, date, location) values (477, 'Cross-group transitional policy', '2016-10-06', 'Lakbok');
insert into tournaments (tournament_id, tournament_name, date, location) values (478, 'Inverse multimedia focus group', '2016-03-13', 'Dehui');
insert into tournaments (tournament_id, tournament_name, date, location) values (479, 'Secured regional encryption', '2017-08-03', 'Sumbawa Besar');
insert into tournaments (tournament_id, tournament_name, date, location) values (480, 'Fundamental actuating superstructure', '2016-04-02', 'Turrialba');
insert into tournaments (tournament_id, tournament_name, date, location) values (481, 'Advanced dynamic encoding', '2016-04-09', 'Bodzanów');
insert into tournaments (tournament_id, tournament_name, date, location) values (482, 'Extended coherent circuit', '2017-03-10', 'Nanhuatang');
insert into tournaments (tournament_id, tournament_name, date, location) values (483, 'Decentralized radical structure', '2017-12-11', 'Riosucio');
insert into tournaments (tournament_id, tournament_name, date, location) values (484, 'Mandatory intangible artificial intelligence', '2016-09-21', 'Karaidel’');
insert into tournaments (tournament_id, tournament_name, date, location) values (485, 'Streamlined stable collaboration', '2017-08-12', 'Angers');
insert into tournaments (tournament_id, tournament_name, date, location) values (486, 'User-friendly even-keeled forecast', '2016-05-08', 'Rouen');
insert into tournaments (tournament_id, tournament_name, date, location) values (487, 'Virtual systemic application', '2016-08-05', 'Íasmos');
insert into tournaments (tournament_id, tournament_name, date, location) values (488, 'Multi-tiered stable initiative', '2017-09-25', 'Ilhabela');
insert into tournaments (tournament_id, tournament_name, date, location) values (489, 'Robust responsive structure', '2016-03-10', 'Clearwater');
insert into tournaments (tournament_id, tournament_name, date, location) values (490, 'Customizable demand-driven secured line', '2017-02-05', 'Yongle');
insert into tournaments (tournament_id, tournament_name, date, location) values (491, 'Configurable 24 hour architecture', '2017-04-22', 'Starý Bohumín');
insert into tournaments (tournament_id, tournament_name, date, location) values (492, 'Horizontal client-driven architecture', '2017-09-12', 'Ogoja');
insert into tournaments (tournament_id, tournament_name, date, location) values (493, 'Progressive high-level help-desk', '2016-10-11', 'Chahār Burj');
insert into tournaments (tournament_id, tournament_name, date, location) values (494, 'Organic composite throughput', '2016-07-28', 'Donan');
insert into tournaments (tournament_id, tournament_name, date, location) values (495, 'Down-sized 24 hour focus group', '2016-09-21', 'Zushi');
insert into tournaments (tournament_id, tournament_name, date, location) values (496, 'Mandatory optimal structure', '2017-01-20', 'Limenária');
insert into tournaments (tournament_id, tournament_name, date, location) values (497, 'Devolved local website', '2016-12-03', 'Xiaolong');
insert into tournaments (tournament_id, tournament_name, date, location) values (498, 'Diverse cohesive archive', '2016-02-23', 'Thị Trấn Yên Thịnh');
insert into tournaments (tournament_id, tournament_name, date, location) values (499, 'Grass-roots solution-oriented emulation', '2017-06-12', 'Chester');
insert into tournaments (tournament_id, tournament_name, date, location) values (500, 'Reactive zero administration success', '2017-05-17', 'Xinzhu');
insert into tournaments (tournament_id, tournament_name, date, location) values (501, 'Managed optimizing customer loyalty', '2016-12-12', 'Montélimar');
insert into tournaments (tournament_id, tournament_name, date, location) values (502, 'Diverse tertiary conglomeration', '2017-02-05', 'Natu');
insert into tournaments (tournament_id, tournament_name, date, location) values (503, 'Reduced directional archive', '2017-12-25', 'Dawwār Tīnjah');
insert into tournaments (tournament_id, tournament_name, date, location) values (504, 'Digitized real-time hierarchy', '2017-06-04', 'Krajan Timur Suger Kidul');
insert into tournaments (tournament_id, tournament_name, date, location) values (505, 'Programmable stable ability', '2017-11-01', 'Hougang');
insert into tournaments (tournament_id, tournament_name, date, location) values (506, 'Ergonomic human-resource groupware', '2016-01-18', 'Rossosh’');
insert into tournaments (tournament_id, tournament_name, date, location) values (507, 'Stand-alone analyzing monitoring', '2016-11-13', 'Dongjiahe');
insert into tournaments (tournament_id, tournament_name, date, location) values (508, 'Upgradable global benchmark', '2017-08-15', 'Xiaohe');
insert into tournaments (tournament_id, tournament_name, date, location) values (509, 'Synchronised 6th generation interface', '2016-07-21', 'Licheń Stary');
insert into tournaments (tournament_id, tournament_name, date, location) values (510, 'Persistent multi-tasking open system', '2017-04-24', 'Huanoquite');
insert into tournaments (tournament_id, tournament_name, date, location) values (511, 'Vision-oriented tertiary process improvement', '2017-02-12', 'Zhongdeng');
insert into tournaments (tournament_id, tournament_name, date, location) values (512, 'Expanded impactful middleware', '2016-09-11', 'Orizari');
insert into tournaments (tournament_id, tournament_name, date, location) values (513, 'Innovative leading edge contingency', '2017-11-04', 'Bāft');
insert into tournaments (tournament_id, tournament_name, date, location) values (514, 'Integrated optimizing workforce', '2017-04-28', 'Tāndo Mittha Khān');
insert into tournaments (tournament_id, tournament_name, date, location) values (515, 'Grass-roots secondary archive', '2016-02-12', 'Lokatadho');
insert into tournaments (tournament_id, tournament_name, date, location) values (516, 'Optional cohesive architecture', '2016-07-08', 'Hongqi');
insert into tournaments (tournament_id, tournament_name, date, location) values (517, 'Secured methodical hierarchy', '2016-02-17', 'Plasy');
insert into tournaments (tournament_id, tournament_name, date, location) values (518, 'Centralized context-sensitive Graphic Interface', '2016-07-14', 'Tanzybey');
insert into tournaments (tournament_id, tournament_name, date, location) values (519, 'Multi-layered hybrid core', '2016-06-30', 'Meziměstí');
insert into tournaments (tournament_id, tournament_name, date, location) values (520, 'Distributed disintermediate architecture', '2017-04-18', 'Dayr as Sūdān');
insert into tournaments (tournament_id, tournament_name, date, location) values (521, 'Self-enabling didactic budgetary management', '2016-07-27', 'Borlänge');
insert into tournaments (tournament_id, tournament_name, date, location) values (522, 'Fundamental bi-directional open system', '2017-09-01', 'Chakari');
insert into tournaments (tournament_id, tournament_name, date, location) values (523, 'Operative asymmetric workforce', '2016-12-06', 'Pancanagara');
insert into tournaments (tournament_id, tournament_name, date, location) values (524, 'Exclusive actuating frame', '2016-08-17', 'Pau');
insert into tournaments (tournament_id, tournament_name, date, location) values (525, 'Expanded hybrid time-frame', '2017-05-30', 'Lappeenranta');
insert into tournaments (tournament_id, tournament_name, date, location) values (526, 'Universal explicit protocol', '2017-07-08', 'Krajan Curahcotok');
insert into tournaments (tournament_id, tournament_name, date, location) values (527, 'Open-source uniform adapter', '2016-04-03', 'Kungsör');
insert into tournaments (tournament_id, tournament_name, date, location) values (528, 'Profound mobile local area network', '2017-05-18', 'La Cruz');
insert into tournaments (tournament_id, tournament_name, date, location) values (529, 'Networked asymmetric benchmark', '2017-04-22', 'Seupakat');
insert into tournaments (tournament_id, tournament_name, date, location) values (530, 'Robust optimal software', '2017-08-12', 'Cañete');
insert into tournaments (tournament_id, tournament_name, date, location) values (531, 'Profit-focused bifurcated ability', '2017-06-21', 'Cielmice');
insert into tournaments (tournament_id, tournament_name, date, location) values (532, 'Diverse fresh-thinking alliance', '2017-03-29', 'Sotteville-lès-Rouen');
insert into tournaments (tournament_id, tournament_name, date, location) values (533, 'Networked analyzing capability', '2017-01-15', 'Rybnik');
insert into tournaments (tournament_id, tournament_name, date, location) values (534, 'Universal impactful attitude', '2016-04-24', 'Huidong');
insert into tournaments (tournament_id, tournament_name, date, location) values (535, 'Configurable contextually-based hub', '2016-09-03', 'Svrljig');
insert into tournaments (tournament_id, tournament_name, date, location) values (536, 'Enhanced executive structure', '2017-07-10', 'Margasana');
insert into tournaments (tournament_id, tournament_name, date, location) values (537, 'Open-architected bottom-line moratorium', '2016-04-08', 'Berber');
insert into tournaments (tournament_id, tournament_name, date, location) values (538, 'Fundamental analyzing time-frame', '2017-07-22', 'Kavajë');
insert into tournaments (tournament_id, tournament_name, date, location) values (539, 'Re-engineered 24 hour structure', '2017-05-07', 'Paços');
insert into tournaments (tournament_id, tournament_name, date, location) values (540, 'Up-sized client-server website', '2016-12-06', 'Neuville');
insert into tournaments (tournament_id, tournament_name, date, location) values (541, 'Down-sized scalable leverage', '2016-07-17', 'Bhamdoun');
insert into tournaments (tournament_id, tournament_name, date, location) values (542, 'Enhanced regional intranet', '2016-09-20', 'Yujia');
insert into tournaments (tournament_id, tournament_name, date, location) values (543, 'User-centric stable groupware', '2016-01-27', 'Kamennyye Potoki');
insert into tournaments (tournament_id, tournament_name, date, location) values (544, 'Open-architected system-worthy challenge', '2017-01-09', 'Chapayeve');
insert into tournaments (tournament_id, tournament_name, date, location) values (545, 'Organic value-added instruction set', '2017-02-17', 'Wuxia');
insert into tournaments (tournament_id, tournament_name, date, location) values (546, 'Enhanced explicit approach', '2016-11-12', 'Xiangshi');
insert into tournaments (tournament_id, tournament_name, date, location) values (547, 'Public-key object-oriented capability', '2016-12-27', 'Ḩalāwah');
insert into tournaments (tournament_id, tournament_name, date, location) values (548, 'Decentralized homogeneous parallelism', '2016-01-20', 'Ardee');
insert into tournaments (tournament_id, tournament_name, date, location) values (549, 'Re-engineered executive function', '2017-06-02', 'Soutocico');
insert into tournaments (tournament_id, tournament_name, date, location) values (550, 'Synergized needs-based framework', '2016-05-27', 'Januária');
insert into tournaments (tournament_id, tournament_name, date, location) values (551, 'Mandatory background functionalities', '2017-06-11', 'Duowa');
insert into tournaments (tournament_id, tournament_name, date, location) values (552, 'Versatile exuding core', '2017-09-20', 'Tilang');
insert into tournaments (tournament_id, tournament_name, date, location) values (553, 'Decentralized object-oriented initiative', '2017-09-23', 'Pejek');
insert into tournaments (tournament_id, tournament_name, date, location) values (554, 'Secured explicit workforce', '2017-08-09', 'Ejidal');
insert into tournaments (tournament_id, tournament_name, date, location) values (555, 'Universal user-facing synergy', '2016-11-07', 'Privolzhsk');
insert into tournaments (tournament_id, tournament_name, date, location) values (556, 'Public-key composite data-warehouse', '2017-03-27', 'Vineuil');
insert into tournaments (tournament_id, tournament_name, date, location) values (557, 'Public-key optimal approach', '2017-07-25', 'Belle-Anse');
insert into tournaments (tournament_id, tournament_name, date, location) values (558, 'Reverse-engineered 3rd generation project', '2016-09-26', 'Wonokerso');
insert into tournaments (tournament_id, tournament_name, date, location) values (559, 'Implemented stable product', '2017-07-02', 'Xinzhou');
insert into tournaments (tournament_id, tournament_name, date, location) values (560, 'Synergized needs-based hub', '2016-05-22', 'Yishi');
insert into tournaments (tournament_id, tournament_name, date, location) values (561, 'Customizable intermediate groupware', '2016-11-14', 'Dangcalan');
insert into tournaments (tournament_id, tournament_name, date, location) values (562, 'Proactive logistical collaboration', '2017-09-24', 'Ulashan');
insert into tournaments (tournament_id, tournament_name, date, location) values (563, 'Stand-alone local product', '2016-03-03', 'Maungatapere');
insert into tournaments (tournament_id, tournament_name, date, location) values (564, 'Fully-configurable systemic parallelism', '2016-01-27', 'Sāh');
insert into tournaments (tournament_id, tournament_name, date, location) values (565, 'Balanced composite forecast', '2016-09-22', 'Khulo');
insert into tournaments (tournament_id, tournament_name, date, location) values (566, 'Cross-platform regional instruction set', '2016-11-14', 'Popova');
insert into tournaments (tournament_id, tournament_name, date, location) values (567, 'Synchronised client-server knowledge user', '2017-12-11', 'Las Palmas');
insert into tournaments (tournament_id, tournament_name, date, location) values (568, 'Focused well-modulated solution', '2017-12-14', 'Bloomington');
insert into tournaments (tournament_id, tournament_name, date, location) values (569, 'Re-contextualized value-added service-desk', '2016-03-05', 'Meiktila');
insert into tournaments (tournament_id, tournament_name, date, location) values (570, 'Innovative multi-state orchestration', '2017-03-05', 'Maikawada');
insert into tournaments (tournament_id, tournament_name, date, location) values (571, 'Triple-buffered content-based open architecture', '2016-09-13', 'Lincoln');
insert into tournaments (tournament_id, tournament_name, date, location) values (572, 'Persistent needs-based portal', '2016-10-29', 'Qaryat ad Da‘īs');
insert into tournaments (tournament_id, tournament_name, date, location) values (573, 'Public-key attitude-oriented open system', '2017-08-24', 'Vĩnh Tường');
insert into tournaments (tournament_id, tournament_name, date, location) values (574, 'User-friendly scalable approach', '2016-02-22', 'Koysinceq');
insert into tournaments (tournament_id, tournament_name, date, location) values (575, 'Function-based 3rd generation solution', '2017-01-07', 'Shahrud');
insert into tournaments (tournament_id, tournament_name, date, location) values (576, 'Quality-focused value-added collaboration', '2017-03-08', 'Guadalupe');
insert into tournaments (tournament_id, tournament_name, date, location) values (577, 'Innovative scalable array', '2016-12-22', 'Kornyn');
insert into tournaments (tournament_id, tournament_name, date, location) values (578, 'Intuitive clear-thinking analyzer', '2017-09-04', 'Ovalle');
insert into tournaments (tournament_id, tournament_name, date, location) values (579, 'Reduced optimal middleware', '2016-12-22', 'Honglin');
insert into tournaments (tournament_id, tournament_name, date, location) values (580, 'Focused bandwidth-monitored architecture', '2016-03-28', 'Banjar');
insert into tournaments (tournament_id, tournament_name, date, location) values (581, 'Profit-focused bottom-line function', '2016-01-29', 'Ar Rifā‘');
insert into tournaments (tournament_id, tournament_name, date, location) values (582, 'User-centric needs-based local area network', '2017-10-09', 'Ath');
insert into tournaments (tournament_id, tournament_name, date, location) values (583, 'Multi-tiered tangible architecture', '2017-05-24', 'Saint-Bruno');
insert into tournaments (tournament_id, tournament_name, date, location) values (584, 'Streamlined regional software', '2016-05-29', 'Jinotepe');
insert into tournaments (tournament_id, tournament_name, date, location) values (585, 'Configurable motivating installation', '2016-10-09', 'Poligny');
insert into tournaments (tournament_id, tournament_name, date, location) values (586, 'Object-based asynchronous project', '2016-07-31', 'Podporozh’ye');
insert into tournaments (tournament_id, tournament_name, date, location) values (587, 'Expanded executive open architecture', '2017-07-10', 'Mendoza');
insert into tournaments (tournament_id, tournament_name, date, location) values (588, 'User-friendly context-sensitive knowledge base', '2017-08-16', 'Jingyang');
insert into tournaments (tournament_id, tournament_name, date, location) values (589, 'Object-based 5th generation workforce', '2016-12-20', 'Ngunguru');
insert into tournaments (tournament_id, tournament_name, date, location) values (590, 'Innovative homogeneous archive', '2016-08-08', 'Yilan');
insert into tournaments (tournament_id, tournament_name, date, location) values (591, 'Customizable bifurcated forecast', '2017-02-22', 'Żarów');
insert into tournaments (tournament_id, tournament_name, date, location) values (592, 'Up-sized 24/7 extranet', '2017-03-22', 'Oekero');
insert into tournaments (tournament_id, tournament_name, date, location) values (593, 'Organized background service-desk', '2016-08-07', 'Kassala');
insert into tournaments (tournament_id, tournament_name, date, location) values (594, 'Integrated secondary success', '2017-04-19', 'Zakupne');
insert into tournaments (tournament_id, tournament_name, date, location) values (595, 'Right-sized hybrid toolset', '2017-02-23', 'Chizhou');
insert into tournaments (tournament_id, tournament_name, date, location) values (596, 'Realigned analyzing application', '2017-07-12', 'Vreshtas');
insert into tournaments (tournament_id, tournament_name, date, location) values (597, 'Inverse cohesive groupware', '2017-04-04', 'Dobryanka');
insert into tournaments (tournament_id, tournament_name, date, location) values (598, 'Robust client-server access', '2016-10-17', 'Pondokkaha Kelod');
insert into tournaments (tournament_id, tournament_name, date, location) values (599, 'Multi-channelled discrete analyzer', '2017-09-02', 'Whitchurch');
insert into tournaments (tournament_id, tournament_name, date, location) values (600, 'Integrated intangible definition', '2016-08-06', 'Kurmuk');
insert into tournaments (tournament_id, tournament_name, date, location) values (601, 'Fundamental multimedia synergy', '2017-12-07', 'Dar Chabanne');
insert into tournaments (tournament_id, tournament_name, date, location) values (602, 'Reactive clear-thinking help-desk', '2016-02-18', 'Kotlovka');
insert into tournaments (tournament_id, tournament_name, date, location) values (603, 'Synergized client-server matrix', '2017-10-16', 'Handaqi');
insert into tournaments (tournament_id, tournament_name, date, location) values (604, 'Vision-oriented 24/7 website', '2017-01-15', 'Baiyinnuole');
insert into tournaments (tournament_id, tournament_name, date, location) values (605, 'Customizable mission-critical challenge', '2016-12-05', 'Iporá');
insert into tournaments (tournament_id, tournament_name, date, location) values (606, 'Right-sized interactive forecast', '2017-04-10', 'Sztum');
insert into tournaments (tournament_id, tournament_name, date, location) values (607, 'Progressive regional approach', '2016-02-12', 'Yuncheng');
insert into tournaments (tournament_id, tournament_name, date, location) values (608, 'Enhanced tangible secured line', '2016-11-03', 'Barrinha');
insert into tournaments (tournament_id, tournament_name, date, location) values (609, 'Fully-configurable next generation challenge', '2016-02-02', 'San Agustín');
insert into tournaments (tournament_id, tournament_name, date, location) values (610, 'Grass-roots intangible help-desk', '2017-04-30', 'Tangjiakou');
insert into tournaments (tournament_id, tournament_name, date, location) values (611, 'Optional logistical forecast', '2017-10-15', 'Huchang');
insert into tournaments (tournament_id, tournament_name, date, location) values (612, 'Reverse-engineered web-enabled focus group', '2016-02-23', 'Kenyau');
insert into tournaments (tournament_id, tournament_name, date, location) values (613, 'User-centric transitional focus group', '2016-06-10', 'Kudang');
insert into tournaments (tournament_id, tournament_name, date, location) values (614, 'Operative composite toolset', '2017-09-24', 'Shiwan');
insert into tournaments (tournament_id, tournament_name, date, location) values (615, 'Monitored systemic complexity', '2016-07-06', 'Cibungur');
insert into tournaments (tournament_id, tournament_name, date, location) values (616, 'Organic dedicated portal', '2016-10-01', 'Ishige');
insert into tournaments (tournament_id, tournament_name, date, location) values (617, 'Reverse-engineered 24 hour benchmark', '2016-08-09', 'Yilan');
insert into tournaments (tournament_id, tournament_name, date, location) values (618, 'Re-engineered mobile utilisation', '2016-11-21', 'Dayeuhluhur');
insert into tournaments (tournament_id, tournament_name, date, location) values (619, 'Public-key needs-based moderator', '2016-11-06', 'Saint-Brieuc');
insert into tournaments (tournament_id, tournament_name, date, location) values (620, 'Extended global function', '2016-06-01', 'Santo Niño');
insert into tournaments (tournament_id, tournament_name, date, location) values (621, 'Reverse-engineered zero defect model', '2016-06-07', 'Mīāndoāb');
insert into tournaments (tournament_id, tournament_name, date, location) values (622, 'Enterprise-wide composite product', '2016-06-26', 'San Diego');
insert into tournaments (tournament_id, tournament_name, date, location) values (623, 'Intuitive transitional architecture', '2017-10-19', 'Aknīste');
insert into tournaments (tournament_id, tournament_name, date, location) values (624, 'Inverse didactic benchmark', '2016-09-06', 'Jubao');
insert into tournaments (tournament_id, tournament_name, date, location) values (625, 'Integrated bandwidth-monitored encoding', '2017-08-25', 'Jingu');
insert into tournaments (tournament_id, tournament_name, date, location) values (626, 'Persevering bandwidth-monitored system engine', '2017-08-06', 'Changtan');
insert into tournaments (tournament_id, tournament_name, date, location) values (627, 'Up-sized directional approach', '2016-09-10', 'Höshööt');
insert into tournaments (tournament_id, tournament_name, date, location) values (628, 'Reactive 3rd generation knowledge base', '2017-07-05', 'Huancapallac');
insert into tournaments (tournament_id, tournament_name, date, location) values (629, 'Persistent object-oriented help-desk', '2016-09-02', 'Canedo');
insert into tournaments (tournament_id, tournament_name, date, location) values (630, 'Open-source mobile standardization', '2017-10-06', 'Wonosari');
insert into tournaments (tournament_id, tournament_name, date, location) values (631, 'Front-line user-facing collaboration', '2017-11-08', 'Kronshtadt');
insert into tournaments (tournament_id, tournament_name, date, location) values (632, 'Grass-roots cohesive contingency', '2016-07-07', 'Bairros');
insert into tournaments (tournament_id, tournament_name, date, location) values (633, 'Object-based client-server alliance', '2017-11-30', 'Kaesŏng');
insert into tournaments (tournament_id, tournament_name, date, location) values (634, 'Virtual leading edge complexity', '2016-02-15', 'Banturkrajan');
insert into tournaments (tournament_id, tournament_name, date, location) values (635, 'Visionary intangible encryption', '2017-10-04', 'Marabahan');
insert into tournaments (tournament_id, tournament_name, date, location) values (636, 'User-centric eco-centric neural-net', '2016-01-24', 'Tumba');
insert into tournaments (tournament_id, tournament_name, date, location) values (637, 'Visionary solution-oriented methodology', '2017-10-03', 'Vila Nova de Milfontes');
insert into tournaments (tournament_id, tournament_name, date, location) values (638, 'Assimilated exuding function', '2017-05-30', 'Bombardopolis');
insert into tournaments (tournament_id, tournament_name, date, location) values (639, 'Self-enabling incremental groupware', '2017-08-05', 'Ush-Tyube');
insert into tournaments (tournament_id, tournament_name, date, location) values (640, 'Reduced methodical access', '2016-05-09', 'Stanisław Dolny');
insert into tournaments (tournament_id, tournament_name, date, location) values (641, 'Implemented full-range strategy', '2017-03-30', 'Meicheng');
insert into tournaments (tournament_id, tournament_name, date, location) values (642, 'Digitized multimedia emulation', '2017-01-22', 'Buchlovice');
insert into tournaments (tournament_id, tournament_name, date, location) values (643, 'Function-based tertiary archive', '2016-05-31', 'Baunu-Timbangan');
insert into tournaments (tournament_id, tournament_name, date, location) values (644, 'Synergized national info-mediaries', '2016-09-29', 'Kebili');
insert into tournaments (tournament_id, tournament_name, date, location) values (645, 'Secured full-range throughput', '2017-12-29', 'Raksajaya');
insert into tournaments (tournament_id, tournament_name, date, location) values (646, 'Reduced 3rd generation pricing structure', '2016-08-13', 'San Narciso');
insert into tournaments (tournament_id, tournament_name, date, location) values (647, 'Polarised fault-tolerant synergy', '2016-08-26', 'Kupino');
insert into tournaments (tournament_id, tournament_name, date, location) values (648, 'Reactive clear-thinking secured line', '2017-03-31', 'Tuban');
insert into tournaments (tournament_id, tournament_name, date, location) values (649, 'Persevering fresh-thinking Graphic Interface', '2017-04-28', 'Linshe');
insert into tournaments (tournament_id, tournament_name, date, location) values (650, 'Fully-configurable transitional groupware', '2016-11-13', 'Suslonger');
insert into tournaments (tournament_id, tournament_name, date, location) values (651, 'Object-based responsive website', '2017-09-17', 'Kalāleh');
insert into tournaments (tournament_id, tournament_name, date, location) values (652, 'Streamlined fault-tolerant analyzer', '2016-09-21', 'Kelo');
insert into tournaments (tournament_id, tournament_name, date, location) values (653, 'Function-based context-sensitive functionalities', '2017-12-12', 'Novi Karlovci');
insert into tournaments (tournament_id, tournament_name, date, location) values (654, 'Organized contextually-based orchestration', '2016-05-19', 'Tunja');
insert into tournaments (tournament_id, tournament_name, date, location) values (655, 'Assimilated well-modulated concept', '2017-02-02', 'Bununu Dass');
insert into tournaments (tournament_id, tournament_name, date, location) values (656, 'Customer-focused empowering pricing structure', '2017-06-04', 'Mamonit');
insert into tournaments (tournament_id, tournament_name, date, location) values (657, 'Open-source fresh-thinking concept', '2016-06-17', 'Vallecillo');
insert into tournaments (tournament_id, tournament_name, date, location) values (658, 'Face to face context-sensitive attitude', '2016-11-10', 'Fada N''gourma');
insert into tournaments (tournament_id, tournament_name, date, location) values (659, 'Public-key bandwidth-monitored hardware', '2016-04-24', 'Shilibu');
insert into tournaments (tournament_id, tournament_name, date, location) values (660, 'Switchable disintermediate success', '2017-03-13', 'Novo Cruzeiro');
insert into tournaments (tournament_id, tournament_name, date, location) values (661, 'Realigned 24/7 productivity', '2017-01-07', 'Kizil');
insert into tournaments (tournament_id, tournament_name, date, location) values (662, 'Multi-lateral human-resource capability', '2017-01-07', 'Quinocay');
insert into tournaments (tournament_id, tournament_name, date, location) values (663, 'Inverse 6th generation info-mediaries', '2016-12-01', 'Oljoq');
insert into tournaments (tournament_id, tournament_name, date, location) values (664, 'Focused uniform adapter', '2017-06-08', 'Russas');
insert into tournaments (tournament_id, tournament_name, date, location) values (665, 'Up-sized attitude-oriented capacity', '2017-06-07', 'Noisy-le-Grand');
insert into tournaments (tournament_id, tournament_name, date, location) values (666, 'Streamlined real-time array', '2016-04-21', 'Bacelo');
insert into tournaments (tournament_id, tournament_name, date, location) values (667, 'Extended coherent structure', '2017-01-24', 'Boa Vista');
insert into tournaments (tournament_id, tournament_name, date, location) values (668, 'Organic user-facing strategy', '2017-07-17', 'Sidu');
insert into tournaments (tournament_id, tournament_name, date, location) values (669, 'Profound transitional function', '2017-06-15', 'Florencio Sánchez');
insert into tournaments (tournament_id, tournament_name, date, location) values (670, 'Adaptive disintermediate intranet', '2016-06-10', 'Krasnoarmiys’k');
insert into tournaments (tournament_id, tournament_name, date, location) values (671, 'Reverse-engineered explicit product', '2017-07-02', 'Cibunar');
insert into tournaments (tournament_id, tournament_name, date, location) values (672, 'Self-enabling real-time intranet', '2017-12-14', 'Helsingborg');
insert into tournaments (tournament_id, tournament_name, date, location) values (673, 'Cloned responsive moderator', '2017-06-22', 'Pretana');
insert into tournaments (tournament_id, tournament_name, date, location) values (674, 'Face to face global implementation', '2016-10-12', 'Sokolo');
insert into tournaments (tournament_id, tournament_name, date, location) values (675, 'Face to face interactive database', '2016-09-06', 'Santa Rita do Passa Quatro');
insert into tournaments (tournament_id, tournament_name, date, location) values (676, 'Expanded client-server success', '2016-06-24', 'Amiens');
insert into tournaments (tournament_id, tournament_name, date, location) values (677, 'Seamless fresh-thinking attitude', '2017-02-20', 'Ripky');
insert into tournaments (tournament_id, tournament_name, date, location) values (678, 'Optional well-modulated focus group', '2017-12-07', 'Miaogou');
insert into tournaments (tournament_id, tournament_name, date, location) values (679, 'Virtual modular interface', '2017-05-23', 'Paratinga');
insert into tournaments (tournament_id, tournament_name, date, location) values (680, 'Monitored next generation encryption', '2017-07-02', 'Kota Kinabalu');
insert into tournaments (tournament_id, tournament_name, date, location) values (681, 'Persevering logistical analyzer', '2017-12-04', 'Beskolen');
insert into tournaments (tournament_id, tournament_name, date, location) values (682, 'Progressive executive data-warehouse', '2017-10-05', 'Nepalgunj');
insert into tournaments (tournament_id, tournament_name, date, location) values (683, 'Cross-group next generation implementation', '2016-08-03', 'Somdet');
insert into tournaments (tournament_id, tournament_name, date, location) values (684, 'Future-proofed scalable leverage', '2017-12-10', 'Kopidlno');
insert into tournaments (tournament_id, tournament_name, date, location) values (685, 'Optional dedicated software', '2016-10-05', 'Arcueil');
insert into tournaments (tournament_id, tournament_name, date, location) values (686, 'Persistent zero defect internet solution', '2016-08-20', 'Dębno');
insert into tournaments (tournament_id, tournament_name, date, location) values (687, 'Organic national success', '2017-10-08', 'Bumbuna');
insert into tournaments (tournament_id, tournament_name, date, location) values (688, 'Persevering mission-critical product', '2017-02-07', 'Zijin');
insert into tournaments (tournament_id, tournament_name, date, location) values (689, 'Reverse-engineered encompassing middleware', '2016-04-05', 'Abovyan');
insert into tournaments (tournament_id, tournament_name, date, location) values (690, 'Enterprise-wide fault-tolerant success', '2017-01-19', 'Florestópolis');
insert into tournaments (tournament_id, tournament_name, date, location) values (691, 'User-friendly mobile complexity', '2017-07-05', 'Reshetylivka');
insert into tournaments (tournament_id, tournament_name, date, location) values (692, 'Object-based dynamic flexibility', '2016-03-13', 'Starobaltachevo');
insert into tournaments (tournament_id, tournament_name, date, location) values (693, 'Exclusive tertiary complexity', '2017-03-04', 'Otwock');
insert into tournaments (tournament_id, tournament_name, date, location) values (694, 'Switchable client-server interface', '2016-01-24', 'Rungkang');
insert into tournaments (tournament_id, tournament_name, date, location) values (695, 'Future-proofed multi-tasking definition', '2017-08-01', 'Zaragoza');
insert into tournaments (tournament_id, tournament_name, date, location) values (696, 'Open-architected modular workforce', '2017-03-24', 'Los Angeles');
insert into tournaments (tournament_id, tournament_name, date, location) values (697, 'Realigned motivating access', '2017-05-05', 'Tabu');
insert into tournaments (tournament_id, tournament_name, date, location) values (698, 'Future-proofed zero tolerance toolset', '2017-06-03', 'Kalmar');
insert into tournaments (tournament_id, tournament_name, date, location) values (699, 'Ergonomic human-resource process improvement', '2017-09-25', 'Aguadulce');
insert into tournaments (tournament_id, tournament_name, date, location) values (700, 'User-centric multi-tasking attitude', '2017-06-06', 'Zhengdonglu');
insert into tournaments (tournament_id, tournament_name, date, location) values (701, 'Organized radical capacity', '2017-01-13', 'Anadia');
insert into tournaments (tournament_id, tournament_name, date, location) values (702, 'Visionary homogeneous throughput', '2016-10-26', 'Puhja');
insert into tournaments (tournament_id, tournament_name, date, location) values (703, 'Object-based motivating strategy', '2017-10-25', 'Suwon-si');
insert into tournaments (tournament_id, tournament_name, date, location) values (704, 'Extended client-server installation', '2017-02-14', 'Klapagading');
insert into tournaments (tournament_id, tournament_name, date, location) values (705, 'Re-engineered asymmetric intranet', '2016-11-29', 'Yangdi');
insert into tournaments (tournament_id, tournament_name, date, location) values (706, 'Organic eco-centric encryption', '2017-01-21', 'Kinshasa');
insert into tournaments (tournament_id, tournament_name, date, location) values (707, 'Cloned disintermediate artificial intelligence', '2016-07-30', 'Gorzów Wielkopolski');
insert into tournaments (tournament_id, tournament_name, date, location) values (708, 'De-engineered composite productivity', '2017-09-01', 'Junik');
insert into tournaments (tournament_id, tournament_name, date, location) values (709, 'Distributed bandwidth-monitored portal', '2017-06-27', 'Jūybār');
insert into tournaments (tournament_id, tournament_name, date, location) values (710, 'Switchable full-range capability', '2016-07-04', 'Áyios Nikólaos');
insert into tournaments (tournament_id, tournament_name, date, location) values (711, 'Fundamental asynchronous focus group', '2017-05-26', 'Shāhpur');
insert into tournaments (tournament_id, tournament_name, date, location) values (712, 'Open-source object-oriented synergy', '2016-12-09', 'Issy-les-Moulineaux');
insert into tournaments (tournament_id, tournament_name, date, location) values (713, 'Grass-roots human-resource hub', '2016-07-26', 'Alavus');
insert into tournaments (tournament_id, tournament_name, date, location) values (714, 'Fundamental neutral model', '2016-07-18', 'Beizhuang');
insert into tournaments (tournament_id, tournament_name, date, location) values (715, 'Customizable incremental instruction set', '2016-12-30', 'Pangatikan');
insert into tournaments (tournament_id, tournament_name, date, location) values (716, 'Open-architected multi-state hub', '2017-12-01', 'Alto do Estanqueiro');
insert into tournaments (tournament_id, tournament_name, date, location) values (717, 'Quality-focused asynchronous moratorium', '2017-03-15', 'Rogowo');
insert into tournaments (tournament_id, tournament_name, date, location) values (718, 'Team-oriented neutral productivity', '2016-12-23', 'Dūāb');
insert into tournaments (tournament_id, tournament_name, date, location) values (719, 'Optimized mission-critical info-mediaries', '2017-09-06', 'Quận Sáu');
insert into tournaments (tournament_id, tournament_name, date, location) values (720, 'Persistent web-enabled open architecture', '2016-11-23', 'Blackfalds');
insert into tournaments (tournament_id, tournament_name, date, location) values (721, 'Progressive cohesive paradigm', '2017-09-22', 'Konary');
